[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
nom = "^4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
